title: Davide Cazzorla
position: Ph.D. Student
affiliation: Univeristy of Bari Aldo Moro
email: d.cazzorla@phd.uniba.it
keywords: machine learning
google_scholar: ./
github_link: https://github.com/davideC00
linkedin: https://www.linkedin.com/in/davide-cazzorla/
cv_link: ./
avatar: ./assets/img/avatar.jpg
#google_analytics: UA-111540567-4
favicon: ./assets/img/favicon.png
favicon_dark: ./assets/img/favicon-dark.png
description: 
canonical: https://strata-academic.yyliu.net/
remote_theme: yaoyao-liu/strata-academic
